name: LightTest
main: ru.beykerykt.minecraft.lightapi.bukkit.ex.BukkitPlugin
version: ${revision}
description: Test plugin for LighterAPI
api-version: 1.15
depend: [ LighterAPI ]
author: BeYkeRYkt
authors: [ other contributors in GitHub ]
website: https://github.com/BeYkeRYkt/LightAPI
commands:
  lighttest:
    description: Main command